# name: Test Workflow

# on:
#   workflow_dispatch:

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello from GitHub Actions"



name: Daily ERCOT Download

on:
  schedule:
    - cron: "0 13 * * *"   # BJ 9pm CA 5am UTC 1pm
  workflow_dispatch:       # 允许你手动点 Run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. 把你的 repo 拉下来
      - uses: actions/checkout@v4

      # 2. 准备 Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. 安装依赖（你只用到了 requests）
      - run: pip install requests

      # 4. 跑你的脚本（就这一行是“核心”）
      - run: python scripts/ASfactors-projected-daily.py
      - run: python scripts/wind-gr.py
      - run: python scripts/solar-gr.py

      # 5. 如果有新文件，就提交回 repo
      - run: |
          git config user.name "github-actionss[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/as_factors_projected
          git diff --cached --quiet || git commit -m "Daily update: Projected AS factors"
          git push
